### ISSUE TITLE
Bundler won't install redstorm

### ISSUE THREAD

**Issue by maruscia** [colinsurprenant/tweitgeist#6]
<fixed>

**Comment by colinsurprenant** [comment]
This only thing I can see without more details on the issue, is that the Bundler Gemfile requires the JRuby platform to install

``` ruby
platform :jruby do
  gem 'redstorm', '~> 0.6.4'
end
```

To run Tweitgeist you will need to use both MRI Ruby and JRuby. MRI Ruby is required for the tweets harvesting and JRuby is for the RedStorm processing. 

I strongly suggest you use one of the Ruby version managers like rbenv https://github.com/sstephenson/rbenv/ or rvm https://rvm.io/ - I  personally now prefer rbenv. You can then use both Rubies side-by-side. (In the tweitgeist README I suggest rvm but since then I have switched to rbenv).

**Comment by maruscia** [comment]
yeah, sorry I resolved but wasn't thereafter able to remove the question after. I didn't "rvm use" the required version of jruby but sticked with a previous one.
